//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TastyRecipes.DBConnection
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TastyRecipesEntities : DbContext
    {
        public TastyRecipesEntities()
            : base("name=TastyRecipesEntities")
        {
            // reference: https://stackoverflow.com/questions/19467673/entity-framework-self-referencing-loop-detected
            Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbRecipe> tbRecipes { get; set; }
        public virtual DbSet<tbUser> tbUsers { get; set; }
    }
}
